function t = Chapter4_116_string_math(str)
% by  bainhome

t=regexp(str,'\w*(\sby)?','match');
arrayfun(@(i)find(strcmp(t(i),...
    regexp(...
        'one two three four five six seven eight nine zero plus minus times multiplied by divided by',...
        '\w+(\sby)?','match'...
          )...
                         )...
                 ),1:numel(t)...
        );
str2='1234567890+-**/';
t=str2num(str2(ans))==numel(str(str~=' '));
end

