function ans = Chapter4_117_string_math(s)
% by  Binbin Qi

ans=str2num(regexprep(s, strsplit(...
'one two three four five six seven eight nine zero plus minus (times|multiplied\sby) divided\sby'), ...
        strsplit('1 2 3 4 5 6 7 8 9 0 + - * /')...
                 )...
        ) == nnz(s~=' ');
end

