function ans = Chapter4_120_string_math(x)
% by  LY Cao

ans=str2num(regexprep(x,strsplit(...
    'zero one two three four five six seven eight nine plus minus times multiplied divided by'),...
    strsplit('0 1 2 3 4 5 6 7 8 9 + - * * / ')...
                 )...
       )==nnz(x~=' ');

