function t = Chapter4_115_string_math(str)
% by  bainhome

t=regexp(str,'\w*','match');
cell2mat(...
    arrayfun(@(i)find(strcmp(t(i),...
        strsplit(...
            'one two three four five six seven eight nine zero plus minus times multiplied divided'...
                )...
                            )...
                     ),1:numel(t),'uni',0....
            )...
        );
str2='1234567890+-**/';
t=str2num(str2(ans))==numel(cell2mat(t));
end

